### ISSUE TITLE
Getting these warning

### ISSUE THREAD

**Issue by kingvinay110** [traptrick/material-table-crud#1]
I am getting these warning

Warning: Failed prop type: The prop `onChangePage` of `ForwardRef(TablePagination)` is deprecated. Use the `onPageChange` prop instead.
Warning: Failed prop type: The prop `onChangeRowsPerPage` of `ForwardRef(TablePagination)` is deprecated. Use the `onRowsPerPageChange` prop instead.
Warning: Failed prop type: The prop `onPageChange` is marked as required in `ForwardRef(TablePagination)`, but its value is `undefined`.

Versions:
"@material-ui/core": "^4.11.3",
    "@material-ui/lab": "^4.0.0-alpha.57",
    "material-table": "^1.69.2",

**Comment by traptrick** [comment]
Just install and use latest versions of all the dependencies brother.
